### PR TITLE
Update 03.05.17

### PR DESCRIPTION
**Pull request by Taxin2012**
* Updated 03 April 2017
* Update by Taxin2012. (http://steamcommunity.com/id/Taxin2012/)
* 
* Features:
* - Added demote system for CP's.
* - Added setting CanDamage. Now you can choose can one CP damage other CP.
* - Added the ability to change the language.
* - Added Russian and English languages.

### CODE REVIEW

**Comment by bamq** [comment]
I like the ideas here, but I'm not sure on a few things.

1. I don't think it's a good idea to notify the entire server.
2. I'm not quite sure why you're making damaged a global variable. Shouldn't the value be separate for each player? You should do something like `att:SetNWInt( "cpantitk_hits", att:GetNWInt( "cpantitk_hits" ) + 1 )` and `if att:GetNWInt( "cpantitk_hits" ) > CPAntiTK.demote then` so it is specific for that player.

**Comment by Taxin2012** [comment]
Updated

**Comment by bamq** [comment]
I don't believe the team ban is actually working. You're calling table.HasValue, which returns either true or false, but teamBan takes a team as its first argument.

**Comment by Taxin2012** [comment]
Updated. I cant do anything with table of jobs.

**Pull request closed without merging**
